version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "hello"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-i5mpf1vktzdt"
s3_prefix = "hello"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
image_repositories = ["HelloWorldFunction=249867148599.dkr.ecr.ap-northeast-1.amazonaws.com/hello5d41402a/helloworldfunction19d43fc4repo"]
